"""
Pydantic schemas for the RevenueOS Demo Scenario Engine.
"""
import uuid
from datetime import datetime
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field


class ScenarioStepResult(BaseModel):
    step_number: int = Field(..., description="Sequential step index (1-indexed)")
    title: str = Field(..., description="Human-readable step title")
    status: str = Field(
        ...,
        description="Step status: completed, blocked, failed, pending_approval, safety_enforced, fallback_success"
    )
    summary: str = Field(..., description="Concise explanation of the step outcome")
    evidence: Dict[str, Any] = Field(
        default_factory=dict,
        description="Granular financial and operational telemetry"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class DemoScenarioMeta(BaseModel):
    id: str = Field(..., description="Scenario identifier")
    name: str = Field(..., description="Scenario title")
    description: str = Field(..., description="Business context and challenge")
    category: str = Field(..., description="Category: degradation, abandonment, subscription, fallback, safety")
    expected_steps: List[str] = Field(..., description="Step titles in execution sequence")
    merchant_scenario_id: str = Field(..., description="Target seeded merchant scenario ID")
    badge: str = Field("ACTIVE", description="UI badge text")
    badge_type: str = Field("info", description="Badge color class: info, warning, danger, success")


class DemoScenarioCatalogResponse(BaseModel):
    scenarios: List[DemoScenarioMeta]


class DemoScenarioRunResponse(BaseModel):
    scenario_id: str = Field(..., description="Identifier of the executed scenario")
    name: str = Field(..., description="Scenario display name")
    merchant_id: uuid.UUID = Field(..., description="Target merchant ID")
    merchant_name: str = Field(..., description="Target merchant name")
    status: str = Field(..., description="Overall execution status")
    steps: List[ScenarioStepResult] = Field(..., description="Chronological execution trace")
    final_summary: str = Field(..., description="Executive summary of business outcome")
    safety_system_proven: bool = Field(
        False,
        description="True if this scenario explicitly verified deterministic policy guardrails"
    )
    key_metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key financial metrics resulting from execution"
    )
    audit_event_ids: List[str] = Field(
        default_factory=list,
        description="IDs of audit records generated by this run"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)
